packages:
  - slides/*
  - slide-decks

catalog:
  '@slidev/cli': ^52.0.0
  '@slidev/theme-default': latest
  '@slidev/theme-seriph': latest
  slidev-theme-dracula: ^0.2.0
  vue: ^3.5.13

onlyBuiltDependencies:
  - playwright-chromium
