packages:
  - slides/**

catalog:
  '@slidev/cli': ^52.12.0
  '@slidev/theme-default': ^0.25.0
  '@slidev/theme-seriph': ^0.25.0
  slidev-theme-dracula: ^0.2.0
  vue: ^3.5.29

onlyBuiltDependencies:
  - playwright-chromium
